development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test: &test
  adapter: sqlite3
  database: :memory: # db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  encoding: unicode
  adapter: postgresql
  username: postgres
  port: 5432
  host: localhost
  database: statustar_development
  password: clearcase

cucumber:
  <<: *test
