development:
  adapter: postgresql
  database: db/development.sqlite3
  database: statustar_development
  pool: 5
  timeout: 5000

test: &test
  adapter: postgresql
  database: statustar_test
  pool: 5
  timeout: 5000

production:
  encoding: unicode
  adapter: postgresql
  username: postgres
  port: 5432
  host: localhost
  database: statustar
  password: clearcase

cucumber:
  <<: *test
